# -*- coding: utf-8 -*-
"""CO2Emission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BRBjiJfY0Q3gNWN9TM6Jl9U6fSgQ0dRI
"""

import pandas as pd

csv_link = 'https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/158/208/original/CO2_Emissions.csv?1760012266'
data = pd.read_csv(csv_link)

data.info()

#finding Nan or missing values in the dataset
print(data.isna().sum())

"""Showing that all the values in the dataset are filled and is already cleaned.
Alreday as shown in the data.info section
"""

categorical_values = data.select_dtypes(include = ['object']).columns

for i in categorical_values:
  if i != 'CO2 Emissions(g/km)' :
    temp = data.groupby(i)['CO2 Emissions(g/km)'].sum().sort_values(ascending=False)
    print(temp.head().to_markdown(), end = '\n\n')

"""### **Q1. Categorical Variable Analysis of CO₂ Emissions**

###Considering only the top 5 contriburer in Each category

#### **1. Make**

Among different vehicle manufacturers, **Ford, Chevrolet, BMW, and Mercedes-Benz** record the highest CO₂ emissions, each exceeding **100,000 g/km**.
This indicates that vehicles from these manufacturers, likely due to larger engine capacities or performance-oriented models, contribute significantly to overall emissions. **GMC** has comparatively lower emissions, suggesting relatively more efficient models or smaller engine configurations.

---

#### **2. Model**

When analyzing emissions at the model level, variations are observed across different versions of the same make.
Models such as the **F-150 FFV 4x4** and **F-150 FFV** show the **highest emission levels** among the group, highlighting the significant contribution of these specific vehicle types to total emissions.
Since multiple models exist under each make, a direct comparison across makes is less meaningful without normalizing for engine size or vehicle class.

---

#### **3. Vehicle Class**

CO₂ emissions vary substantially across vehicle classes.
The **SUV–Small** category exhibits the **highest average emissions**, followed by **Mid-Size** and **Standard SUV** classes.
In contrast, **Compact** and **Full-Size** vehicles produce comparatively lower emissions.
This pattern reflects the general trend that larger, heavier vehicles with higher power outputs emit more CO₂.

---

#### **4. Transmission**

Emissions appear to correlate with transmission type.
Vehicles equipped with **AS8 (Automatic 8-speed)** and **AS6 (Automatic 6-speed)** transmissions show the **highest CO₂ emissions**, both exceeding **300,000 g/km**.
This may be attributed to higher performance tuning or larger engine sizes associated with these transmission systems.
Meanwhile, **manual transmissions (M6)** and **A8** systems demonstrate relatively lower emissions, indicating more efficient performance configurations.

---

#### **5. Fuel Type**

Fuel type has a pronounced influence on CO₂ output.
Vehicles using **Fuel Type X and Z** display the **highest emission levels** (above **850,000 g/km**), whereas those using **Fuel Type N** have the **lowest** (around **213 g/km**).
This suggests that **Fuel Type N** may correspond to electric or hybrid configurations, while **X and Z** likely represent traditional fossil fuels such as petrol or diesel.

---

### **Summary Insight**

Overall, the analysis reveals that:

* **Make:** Premium and performance-oriented brands tend to emit more CO₂.
* **Model:** Larger pickup and SUV variants contribute disproportionately.
* **Vehicle Class:** SUV categories are the most emission-intensive.
* **Transmission:** Automatic multi-speed systems are associated with higher emissions.
* **Fuel Type:** Conventional fuels (X, Z) significantly drive emission levels.

These insights can support further model development or policy recommendations focused on emission reduction strategies, especially targeting **SUV and automatic transmission vehicles using high-emission fuel types**.



"""

numeric_values = data.select_dtypes(include = ['float64','int64']).columns
numeric_values = numeric_values.drop('CO2 Emissions(g/km)')
for i in numeric_values :
  temp = data.groupby(i)['CO2 Emissions(g/km)'].sum().sort_values(ascending=False)
  print(temp.head().to_markdown(), end = '\n\n')

"""Perfect — this second image contains numerical features (continuous variables) like **Engine Size, Cylinders, Fuel Consumption**, and **Gears** in relation to **CO₂ emissions**.

Here’s a **professionally written analytical interpretation** consistent with your previous analysis format 👇

---

### **Numerical Variable Analysis of CO₂ Emissions**

#### **1. Engine Size (L)**

A clear **inverse relationship** is not immediately visible, but overall, **larger engine sizes** tend to show **higher CO₂ emissions**.

* Vehicles with an **engine size of 2L** emit the most CO₂ (**306,695 g/km**), followed by **3L (207,403 g/km)** and **3.6L (143,111 g/km)**.
* As the engine size increases to **5.3L**, emissions decrease to **90,424 g/km**, which may be influenced by **engine efficiency improvements** or **fuel type differences** among these models.
  Overall, **engine capacity** remains a major determinant of emission levels due to its direct effect on fuel combustion rates.

---

#### **2. Cylinders**

The number of cylinders generally correlates with fuel consumption and emission output.

* **4-cylinder** and **6-cylinder** engines record the **highest emissions** (around **650,000 g/km**), while **8-cylinder** and **12-cylinder** engines show somewhat lower values (449,508 and 57,536 g/km respectively).
* This variation suggests that **engine design efficiency** and **vehicle class distribution** may play a stronger role than cylinder count alone.
  Nonetheless, engines with **more cylinders** typically consume more fuel and therefore have a **higher emission potential**.

---

#### **3. Fuel Consumption – City (L/100 km)**

Fuel consumption in urban driving conditions has a **strong positive relationship** with CO₂ emissions.

* The highest city fuel consumption (**13.7 L/100 km**) corresponds to **27,312 g/km**, while **12.4 L/100 km** corresponds to **30,632 g/km**.
* Although minor fluctuations appear, the overall trend indicates that **as city fuel consumption increases, CO₂ emissions rise correspondingly**, reflecting the impact of frequent stops, idling, and acceleration in city driving.

---

#### **4. Fuel Consumption – Highway (L/100 km)**

For highway driving, the trend remains consistent—**higher fuel consumption equals higher emissions**.

* Vehicles consuming **7.8 L/100 km** emit **45,792 g/km**, while those consuming **9.2 L/100 km** emit **39,398 g/km**.
* This relatively lower variation implies that **steady-speed driving on highways** yields **more stable and efficient fuel use**, hence slightly reduced CO₂ output compared to city conditions.

---

#### **5. Fuel Consumption – Combined (L/100 km)**

Combined consumption (average of city and highway) provides a reliable indicator of real-world performance.

* CO₂ emissions range between **30,963 – 32,594 g/km**, showing a **direct linear relationship** with combined fuel consumption.
* Vehicles with **higher combined fuel usage (11 L/100 km)** display **higher emissions**, reaffirming that **fuel efficiency improvements** directly translate into emission reductions.

---

#### **6. Fuel Consumption – Combined (mpg)**

When measured in **miles per gallon**, CO₂ emissions show an **inverse relationship** with fuel efficiency.

* As mileage improves from **22 mpg to 27 mpg**, emissions decline from **134,951 g/km to 112,349 g/km**.
* This clearly indicates that **better fuel efficiency (higher mpg)** results in **lower CO₂ emissions**, aligning with standard environmental performance metrics.

---

#### **7. Gears**

Transmission gearing shows noticeable variation in emission levels:

* Vehicles with **6 gears** have the **highest CO₂ emissions (793,800 g/km)**, while those with **5 gears** emit the least (**70,537 g/km**).
* A higher number of gears (8 or 9) tends to correspond with **moderate emission levels**, possibly due to **optimized gear ratios improving engine efficiency**.
  This suggests that while older transmissions with fewer gears may be less efficient, mid-range gear systems (6–8) used in high-performance vehicles can also contribute to higher emissions.

---

### **Summary Insight**

* **Engine size, cylinders, and fuel consumption metrics** are the most direct influencers of CO₂ emissions.
* **Higher engine displacement** and **greater city fuel consumption** result in elevated emission levels.
* **Fuel efficiency (mpg)** shows a strong **negative correlation** with emissions, confirming that improved mileage significantly reduces environmental impact.
* **Transmission and gear configurations** affect emissions based on vehicle tuning and performance objectives.

Overall, these findings reaffirm that **vehicle design efficiency, fuel economy, and drivetrain configuration** play crucial roles in determining CO₂ emission intensity.

---

### **Q2. Cleaning of the Dataset**
"""

### Finding the number of the unique values for each column

data[categorical_values].nunique()

"""### **Cleaning of the Data by converting all the characters to lowercase , removing white spaces and special characters**"""

### Removal of any Blank spaces and special characters from the values and converting them to lower case
data['Gears'] = data['Transmission'].str.extract(r'(\d+)').astype(float)

for i in categorical_values:
  data[i] = data[i].str.lower()
  data[i] = data[i].str.replace(r'\s+', ' ', regex=True)
  data[i] = data[i].str.replace(' ','',regex=True)
  data[i] = data[i].str.strip()
  data[i] = data[i].str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)
  #print(i,"     ",data[i].nunique())

"""### **Binning of the values which have less than 10 instances as the number of unique values in the dataset is to large and the values with lower than 10 instances would not contribute significantly**"""

def bin_rare_categories(series, threshold_count):
    counts = series.value_counts()

    rare_values = counts[counts < threshold_count].index

    return series.replace(rare_values, 'other')

data['model_consolidated'] = data['Model'].apply(lambda x: ' '.join(str(x).split()[:2]))

MODEL_THRESHOLD = 10

data['model_binned'] = bin_rare_categories(data['model_consolidated'], threshold_count=MODEL_THRESHOLD)

print(f"Original unique Models: {data['Model'].nunique()}")
print(f"Binned unique Models: {data['model_binned'].nunique()}")

#Drop of the Model Row after the binning has been done
data.drop(columns=['Model','model_consolidated'],inplace=True)

data.head()

"""### **Q7. Preparing model by doing the cleaning and imbeding Variance Inflation Factor**
### **Standardization of the Numerical Values**
"""

from sklearn.preprocessing import StandardScaler
df = data.copy()

scaler = StandardScaler()

#Scaling the numerical values according to the StandardScaler

df[numeric_values] = scaler.fit_transform(df[numeric_values])

df.head()

import numpy as np
df_encoded = pd.get_dummies(df, categorical_values,drop_first=True,dtype=np.int32)
#df_encoded = df_encoded.drop(columns=['Transmission'])
print(df_encoded.shape)
df_encoded.head()

from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.api import add_constant
from sklearn.linear_model import LinearRegression
y = df_encoded['CO2 Emissions(g/km)']
X = df_encoded.drop(columns=['CO2 Emissions(g/km)'])

"""
### **Calculating Variance Inflation Factor for various variables to reduce the collinearity or the equation**"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

def vif_filter(X, thresh=7):

    X = X.select_dtypes(include=[np.number]).dropna().copy()
    dropped = True

    while dropped:
        dropped = False
        vif = []

        for i in range(X.shape[1]):
            y = X.iloc[:, i]
            X_other = X.drop(X.columns[i], axis=1)
            model = LinearRegression().fit(X_other, y)
            r2 = model.score(X_other, y)
            vif.append(np.inf if r2 == 1 else 1 / (1 - r2))

        max_vif = max(vif)
        if max_vif > thresh:
            drop_col = X.columns[vif.index(max_vif)]
            print(f"Dropping '{drop_col}' with VIF: {max_vif:.2f}")
            X = X.drop(columns=[drop_col])
            dropped = True

    return X



# Example call
X = X.select_dtypes(include=[np.number])
X_filter = vif_filter(X)
X.shape

"""### **Saving the Columns which were present after the removal of the interdependent variables, so that the calculation does not need to be done multiple times.**"""

X = X.select_dtypes(include=[np.number])
file_path = 'index.txt'
with open('index.txt', 'r', encoding='utf-8-sig') as file:
    raw_lines = file.readlines()

# -----------------------------------

index_list = []

for line in raw_lines:
    # 2. Clean the line: remove leading/trailing whitespace (including the newline character).
    cleaned_line = line.strip()

    # 3. Remove the single quotes (') that seem to enclose the indices.
    # We replace ' with an empty string, which results in a comma-separated string.
    no_quotes = cleaned_line.replace("'", "")

    # 4. Split the string by the comma delimiter and extend the list.
    # This ensures each individual index name is a separate item in the list.
    # We use a list comprehension to also strip any remaining spaces around commas.
    indices = [item.strip() for item in no_quotes.split(',') if item.strip()]

    index_list.extend(indices)

# The 'index_list' now contains all the individual index names.
print(f"Total indices read: {len(index_list)}")
X = X[index_list]
X.shape

"""### After the overall cleaning of the data, Now the data is ready to be processed and can be used for calculations to be done"""

print(X_filter.shape,data.shape)

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

model = LinearRegression()
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model.fit(X_train,y_train)
model.score(X_test,y_test)

"""### According to the training done, the accuracy of the model is around 95% which tends to be a good score"""

coeff_df = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_
})

coeff_df = coeff_df.sort_values(by='Coefficient',ascending=False)
coeff_df

"""Because features are on the same scale, the coefficient's absolute value indicates the feature's relative strength in predicting $\text{CO}_2$ emissions.

**Q3.** Relationships between various vehicle features and CO₂ emissions , attributes appear to have stronger influence on emission levels .
"""

import statsmodels.api as sm

X_train_with_const = sm.add_constant(X_train)
ols_model = sm.OLS(y_train,X_train_with_const).fit()

#Finding P_Values of the variables for the analysis of the dependencies of the outcome on the variables
p_values = ols_model.pvalues.reset_index()
p_values.columns = ['Feature', 'P-Value']

#showing only the variables which have P_values higher than 0.05 as the variables would have less impact on the outcome
insignificant_features = p_values[p_values['P-Value'] >= 0.05].sort_values(by='P-Value', ascending=False)
print(insignificant_features.to_markdown(index=False))

print(insignificant_features.count() , insignificant_features.head())

"""### **Out of the given features, 155 features do not contribute significantly or have no effect on the total CO2 emissions, Among which Fuel Type has the least contribution as we can see all the fuel type have very high P_value or in the hypothesis testing they fail the hypothesis that the change in the type of Fuel contribute to the change in the CO2 Emissions made by the car**

### **where as the Make_bugatti	85.371370 ,Model_vanpassenger	74.696689, Model_vancargo	49.353033, Fuel Type_tundra4wd	35.242639, Make_lamborghini	31.203165 have a very significant +ve contribution in the emissions made And Fuel Type_veloster	-22.562997 , Fuel Type_corvette	-25.977558 , Fuel Type_continentalgt	-30.111808,	Fuel Consumption Comb (mpg)	-38.989012 , Transmission_e	-55.862883 have -ve contribution in the emissions as the values of the feature grows**

**Q4.**  visual summaries that reveal how emission levels change with respect to different numerical variables in the dataset
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np # numpy is needed for np.ceil

# --- ASSUMING 'data' IS THE DATAFRAME ---

# 1. Standardize column names for safe access
data = data.rename(columns={
    'CO2 Emissions(g/km)': 'co2_emissions'
}, errors='ignore') # Use errors='ignore' in case it was already renamed

TARGET_COL = 'co2_emissions'

# 2. Correctly select numerical columns and filter out the target
n_values_cols = data.select_dtypes(include=['float64','int64']).columns
n_values_cols = [col for col in n_values_cols if col != TARGET_COL]

# 3. Use the list of column names for iteration and calculation
numeric_data_df = data[n_values_cols] # Use data[n_values_cols] to get the DataFrame data

num_features = len(n_values_cols) # FIX: Use n_values_cols here
ncols = 3
nrows = int(np.ceil(num_features / ncols))

fig, axes = plt.subplots(nrows=nrows, ncols=ncols, figsize=(6 * ncols, 6 * nrows))
axes = axes.flatten()


for i, col in enumerate(n_values_cols): # FIX: Loop through the list of column names
    # FIX: Use the actual data from the 'data' DataFrame
    axes[i].scatter(data[col], data[TARGET_COL], c='darkblue', alpha=0.6, marker = 'o')

    # Set titles and labels for clarity
    axes[i].set_title(f'CO₂ vs. {col.replace("_", " ").title()}', fontsize=12)
    axes[i].set_xlabel(col.replace("_", " ").title(), fontsize=10)
    axes[i].set_ylabel('CO₂ Emissions (g/km)', fontsize=10)
    axes[i].grid(True, linestyle='--', alpha=0.5)


for j in range(num_features, nrows * ncols):
    fig.delaxes(axes[j])

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.suptitle('Relationship Between Numerical Features and CO₂ Emissions', fontsize=16, y=1.02)
plt.savefig('numerical_features_scatter_plots_fixed.png')
# Note: plt.show() is removed as per the guidelines, but will execute in a standard Colab environment.
# plt.show()

"""## Analysis of Vehicle Features and $\mathbf{CO_2}$ Emissions


***

### 1. Primary Drivers of $\mathbf{CO_2}$ Emissions

The most direct and significant relationships observed are strong **positive correlations**, where an increase in the vehicle's capacity or consumption metrics leads directly to an increase in $\text{CO}_2$ emissions.

---

### 2. Physical and Operational Dependency

The analysis confirms a sequential dependency among the physical features of the vehicle:

* **Engine Capacity $\rightarrow$ Fuel Consumption $\rightarrow$ Emissions:** As the physical **Engine Size** and **Cylinder Capacity** of the vehicle grow, the engine's capacity requirement for fuel also inherently increases, leading directly to elevated **Fuel Consumption**.
* This elevated fuel consumption is the mechanical source of the **increased $\mathbf{CO_2}$ Emissions**.

***

### 3. Observed Efficiency (Inverse Relationship)

While $\text{CO}_2$ emissions increase with consumption (L/100 km), they naturally decline with efficiency metrics:

* **Combined Fuel Consumption (Inverse Metric):** $\text{CO}_2$ emissions show a **strong decline** when correlated against the **Combined Fuel Consumption (mpg)** metric. This is because **miles per gallon (mpg)** is an inverse measure of consumption; high efficiency (high mpg) means less fuel burned, resulting in lower $\text{CO}_2$ output.

### **Q5.** Comparison of $\text{CO}_2$ Emissions classified according to the Vehicle Class and the Fuel Type the vehicle uses
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# --- ASSUMING 'data' IS THE DATAFRAME ---

# 1. Prepare Data and Fix Column Names (Essential for robustness)
# The full solution requires defining nrows, ncols, and cleaning columns.
data = data.rename(columns={
    'CO2 Emissions(g/km)': 'co2_emissions',
    'Fuel Type': 'Fuel Type',
    'Vehicle Class': 'Vehicle Class'
}, errors='ignore')

# Clean Fuel Type and Vehicle Class for grouping
data['Fuel Type'] = data['Fuel Type'].str.strip()
data['Vehicle Class'] = data['Vehicle Class'].str.strip()

# Calculate counts for Pie Charts (Proportions)
fuel_counts = data['Fuel Type'].value_counts()
vehicle_counts = data['Vehicle Class'].value_counts()

# 2. Setup Subplots
analysis = ['Vehicle Class', 'Fuel Type']
num_plots = len(analysis)
nrows = 1
ncols = num_plots

fig, axes = plt.subplots(nrows=nrows, ncols=ncols, figsize=(10, 5))
axes = axes.flatten()

axes[0].pie(
    vehicle_counts,
    labels = vehicle_counts.index,
    autopct='%1.1f%%', # Added autopct for percentages
    startangle=90,
    wedgeprops={'edgecolor': 'black', 'linewidth': 0.5}
)
axes[0].set_title('Vehicle Distribution by Class', fontsize=12)


axes[1].pie(
    fuel_counts,
    labels=fuel_counts.index,
    autopct='%1.1f%%',
    startangle=90,
    wedgeprops={'edgecolor': 'black', 'linewidth': 0.5}
)
axes[1].set_title('Vehicle Distribution by Fuel Type', fontsize=12)


plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.suptitle('Distribution of Vehicles by Class and Fuel Type', fontsize=16, y=1.02)
plt.show()

"""
## 1. Vehicle Class Analysis (Emissions by Sales Volume)

The total emissions caused by a vehicle class are driven more by **sales volume and common usage** than by individual vehicle efficiency.

- **High Total Emissions:** **Small, Midsize, Compact, and Standard** vehicles contribute the highest *total* $\text{CO}_2$ emissions.
    - **Reasoning:** These are the primary vehicles sold to the general public and used on a regular basis (commuting, errands). Their sheer numbers and constant use lead to the largest cumulative $\text{CO}_2$ output, even if they are individually more fuel-efficient than large trucks.
- **Low Total Emissions:** Vehicle classes like **Two-seater, Minivan, and Minicompact** cause a negligible amount of total $\text{CO}_2$ emissions.
    - **Reasoning:** This is primarily due to their **low sales volume** and niche usage, and in the case of Minicompacts, often higher mileage efficiency per unit.

***

## 2. Fuel Type Analysis (Emissions by Market Share)

The distribution charts clearly show that the vast majority of pollution is concentrated in the most common fuel types.

- **Primary Pollution Sources (Type X & Z):** Fuel Types **X** (Regular Unleaded Gasoline) and **Z** (Premium Unleaded Gasoline) cover the most significant amount of pollution caused.
    - **Reasoning:** This dominance reflects the **high market share** of gasoline-powered vehicles and their fundamental role as the primary transport fuel.
- **Negligible Emission Sources:** All other fuel types (including Diesel, Ethanol (E), etc.) have a negligible amount of total emissions.
    - **Reasoning:** Despite some alternative fuels having high *per-unit* emissions, their minimal market penetration and usage volume ensure their **overall cumulative impact is extremely small** in the context of this dataset."""

data.info()

"""### **Q6.** Analysis of vehicle class which produces High or Low amounts of Emissions with respect to other vehicles of the same category."""

data.groupby('Vehicle Class')['co2_emissions'].sum().sort_values(ascending = False)

"""from the above grouping and the chart , value analysis we can see that the suvsmall and midsize produces the most amount of emissions where as stationwagonmidsize and vancargo produces the least amount of emimssions.

**Analysing these 4 categories**

According to the data given we count that the fuel consumption comb (L/100km) multiplied by the total number of vehicles would give the total consumption made by the category of vehicles and would be the best reliable numerical factor that could be used for the amount of fuel emissions made by the car and the Fuel Type which the vehicle uses would provide the most suitable categorical factor for emissions
"""

vehicle = data.groupby('Vehicle Class')['Vehicle Class'].count().sort_values(ascending = False)
consumption = data.groupby('Vehicle Class')['Fuel Consumption Comb (L/100 km)'].count().sort_values(ascending = False)
x = pd.DataFrame(vehicle*consumption)
vehicle

"""### The Analysis could be made that the suvsmall and midsize vehicle have the highest number of vehicles on road, which leads to the total amount of contribution for emissions made by these types of vehicles the highest and the van cargo and the stationwagonmidsize have the lowest number of vehicles leading to the lowest number of contributions in the emissions."""

categories = data[data['Vehicle Class'].isin(['suvsmall','midsize'])]
#categories.info()
print(categories.groupby('Make')['Vehicle Class'].count().sort_values(ascending = False).head())
categories.groupby('Make')['Fuel Consumption Comb (L/100 km)'].mean().sort_values(ascending = False)

"""### 1. The Fuel Consumed by the suvsmall and midsize vehicle is mostly the x or z type, which are the fuel types which causes the most amount of polution"""



numeric_values = df.select_dtypes(include = ['int64','float64'])

plt.figure(figsize=(10,8))
sns.heatmap(numeric_values.corr(),annot = True, cmap='coolwarm',center=0, linewidths = 1, fmt='.2f')
plt.title('Correlation Heatmap (Numerical Features Only)')
plt.tight_layout()
#plt.xticks(rotation = 25)
plt.show()

"""### The heatmap visually identifies the sources of multicollinearity (VIF $> 10$) for the Features. Fuel Consumption Comb (L/100 km) vs. Fuel Consumption Comb (mpg): These two features are mathematically linked as they are inverse measurements of the same quantity (efficiency). giving very high -ve correlation strength,

###Engine Size vs Cylinders: These features measure the same underlying concept (vehicle power/capacity) and compete to explain variance, leading to unstable coefficients. One must be dropped.

### **As for the relationship of the features with the amount of Emissions caused:**
### All the features ('Engine Size(L)', 'Cylinders', 'Fuel Consumption City (L/100 km)', 'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)') are major contributors for the emissions where as 'Fuel Consumption Comb (mpg)' being inversly related to Fuel Consumption Comb (L/100 km) has a negative relation with CO2 Emissions(g/km) and 'Gears' contribute very little to the amount of the Emissions caused as the it depends at which gear does the driver rides the viehicle and not the amount of gears present in it
"""

ols_model.summary()

